### ISSUE TITLE
Template filenames with non-ASCII characters break compilation

### ISSUE THREAD

**Issue by dataflake** [malthe/chameleon#284]
This is a blocking issue in Zope were we now allow Zope object ids with non-ascii characters.

Essentially, when I create a Page Template in Zope with a non-ASCII ID then I'll get an error message about failing page template compilation, even if I remove all contents and the template just contains an empty string:

```
<!-- Page Template Diagnostics
 Compilation failed
 builtins.UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 2: ordinal not in range(128)
-->
```
The error happens here on line 313 during the force-encoding to ASCII:

https://github.com/malthe/chameleon/blob/af889be0247e24c5df5574979c36bdf9e2ed4ba7/src/chameleon/zpt/template.py#L311-L314

That's because the return value of `digest` may now contain non-ASCII characters because `filename` contains them:

https://github.com/malthe/chameleon/blob/af889be0247e24c5df5574979c36bdf9e2ed4ba7/src/chameleon/template.py#L250-L258

**Comment by malthe** [comment]
You experience this with Python 2 and/or 3?

**Comment by dataflake** [comment]
The original issue at zopefoundation/Zope#382 mentions both Python 2 and 3

**Comment by dataflake** [comment]
We're pinning version 3.5, just FYI

**Comment by malthe** [comment]
This might work:
```diff
diff --git a/src/chameleon/zpt/template.py b/src/chameleon/zpt/template.py
index ae3d5d4..a2d79c9 100644
--- a/src/chameleon/zpt/template.py
+++ b/src/chameleon/zpt/template.py
@@ -310,7 +310,7 @@ class PageTemplate(BaseTemplate):
 
     def digest(self, body, names):
         hex = super(PageTemplate, self).digest(body, names)
-        digest = md5(hex.encode('ascii'))
+        digest = md5(hex)
         digest.update(';'.join(names).encode('utf-8'))
 
         for attr in (
```

**Comment by dataflake** [comment]
Hold on, I'll check

**Comment by malthe** [comment]
I changed it a little for the PR ^^^ – but it needs a test.

**Comment by dataflake** [comment]
This appears to work on Python 2, but on Python 3 I am getting a traceback ending like this"

``` 
  File "/Users/jens/src/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 275, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/Users/jens/src/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 355, in pt_render
    result = PageTemplate.pt_render(self, source, extra_context)
  File "/Users/jens/src/Zope/src/Products/PageTemplates/PageTemplate.py", line 83, in pt_render
    showtal=showtal)
  File "/Users/jens/src/.eggs/zope.pagetemplate-4.4.1-py3.7.egg/zope/pagetemplate/pagetemplate.py", line 129, in pt_render
    raise PTRuntimeError(str(self._v_errors))
zope.pagetemplate.pagetemplate.PTRuntimeError: ['Compilation failed', 'builtins.TypeError: Unicode-objects must be encoded before hashing']
```

**Comment by malthe** [comment]
Can you try with the changeset in https://github.com/malthe/chameleon/pull/285?

**Comment by dataflake** [comment]
Yes, will do. This is the real underlying traceback, btw:

```
Traceback (most recent call last):
  File "/Users/jens/src/.eggs/zope.pagetemplate-4.4.1-py3.7.egg/zope/pagetemplate/pagetemplate.py", line 230, in _cook
    source_file, self._text, pt_engine, self.content_type)
  File "/Users/jens/src/Zope/src/Products/PageTemplates/engine.py", line 128, in cook
    encoding='utf-8', extra_builtins=cls.extra_builtins,
  File "/Users/jens/src/.eggs/Chameleon-3.5-py3.7.egg/chameleon/zpt/template.py", line 199, in __init__
    super(PageTemplate, self).__init__(body, **config)
  File "/Users/jens/src/.eggs/Chameleon-3.5-py3.7.egg/chameleon/template.py", line 128, in __init__
    self.write(body)
  File "/Users/jens/src/.eggs/Chameleon-3.5-py3.7.egg/chameleon/template.py", line 221, in write
    self.cook(body)
  File "/Users/jens/src/.eggs/Chameleon-3.5-py3.7.egg/chameleon/template.py", line 157, in cook
    digest = self.digest(body, names)
  File "/Users/jens/src/.eggs/Chameleon-3.5-py3.7.egg/chameleon/zpt/template.py", line 313, in digest
    digest = md5(hex)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by dataflake** [comment]
#285 appears to fix it on both Python 2 and Python 3, yes.
