### ISSUE TITLE
Add support for pathlib-based paths

### ISSUE THREAD

**Issue by markkuleinio** [malthe/chameleon#342]
`Pathlib` (https://docs.python.org/3/library/pathlib.html) was introduced in Python 3.4, I'm suggesting adding support for it when handling file paths in `chameleon`.

The benefit of using `pathlib.Path` is user-friendly interface for OS-independent path manipulations because you can use "/" operator to concatenate paths instead of using separate `os.path.join()` function calls (see `templates_dir` below).

`Pathlib` paths are also supported in Python standard library modules and functions (`open()` and other similar cases), so using `pathlib.Path` objects (instead of strings) is transparent for the user in the usual cases where file paths are used in Python.

Example `chamtest.py` (with `testtemplate.pt` in `templates` directory):

```
from pathlib import Path

from chameleon import PageTemplateLoader

current_dir = Path(__file__).resolve().parent
print("=== Current absolute directory:", current_dir)

templates_dir = current_dir / "templates"
print("=== Templates directory:", templates_dir)

print("=== Type:", type(str(templates_dir)))
templates = PageTemplateLoader(str(templates_dir))
template = templates["testtemplate.pt"]
print("=== stringified template path loaded ok")

print("=== Type:", type(templates_dir))
templates = PageTemplateLoader(templates_dir)
template = templates["testtemplate.pt"]
print("=== template path never loaded")
```

Results:

```
(venv)$ python3 chamtest.py
=== Current absolute directory: /home/markku/devel/cham-test
=== Templates directory: /home/markku/devel/cham-test/templates
=== Type: <class 'str'>
=== stringified template path loaded ok
=== Type: <class 'pathlib.PosixPath'>
Traceback (most recent call last):
  File "chamtest.py", line 18, in <module>
    template = templates["testtemplate.pt"]
  File "/home/markku/devel/cham-test/venv/lib/python3.7/site-packages/chameleon/zpt/loader.py", line 28, in load
    return super(TemplateLoader, self).load(filename, cls)
  File "/home/markku/devel/cham-test/venv/lib/python3.7/site-packages/chameleon/loader.py", line 45, in load
    self.registry[args] = template = func(self, *args, **kwargs)
  File "/home/markku/devel/cham-test/venv/lib/python3.7/site-packages/chameleon/loader.py", line 102, in load
    for path in self.search_path:
TypeError: 'PosixPath' object is not iterable
(venv)$
```

**Comment by malthe** [comment]
This is a good idea – I suppose it might be nice to use this as an excuse to add type specs to the main interfaces.

**Comment by markkuleinio** [comment]
Yeah and to be extra clear for other readers, I'm suggesting accepting both `str` and `pathlib.Path` (in type hint something like `Union[str, pathlib.Path]`).

**Comment by malthe** [comment]
@markkuleinio note that `search_path` must be an iterable, e.g. `search_path=[my_path1, my_path2]`.

Ideally there would be some type-checking, but this is old-school Python and we haven't gotten around to adding any typings and there's not a lot of arguments checking either.
