### ISSUE TITLE
 i18n:target undefined variable

### ISSUE THREAD

**Issue by ale-rt** [malthe/chameleon#368]
I found out that writing something like `i18n:target="it"` breaks rendering the template:
```shell
[ale@flo chameleon]$ cat a.pt 
<html i18n:target="it">
  <body>
    <h1>Hello, ${'world'}!</h1>
    <table>
      <tr tal:repeat="row 'apple', 'banana', 'pineapple'">
        <td tal:repeat="col 'juice', 'muffin', 'pie'">
           ${row.capitalize()} ${col}
        </td>
      </tr>
    </table>
  </body>
</html>

[ale@flo chameleon]$ cat test.py 
from chameleon import PageTemplate
with open("a.pt") as f:
    print(PageTemplate(f.read())())

[ale@flo chameleon]$ python test.py
Traceback (most recent call last):
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/template.py", line 190, in render
    self._render(stream, econtext, rcontext)
  File "a54623d9770b0e62dfab8350116320b1.py", line 98, in render
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/utils.py", line 426, in get_name
    raise NameError(key)
NameError: it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ale/Code/plone/packages/chameleon/test.py", line 3, in <module>
    print(PageTemplate(f.read())())
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/template.py", line 143, in __call__
    return self.render(**kwargs)
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/zpt/template.py", line 298, in render
    return super().render(**_kw)
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/template.py", line 214, in render
    raise_with_traceback(exc, tb)
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/utils.py", line 20, in raise_with_traceback
    raise exc
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/template.py", line 190, in render
    self._render(stream, econtext, rcontext)
  File "a54623d9770b0e62dfab8350116320b1.py", line 98, in render
  File "/home/ale/Code/plone/packages/chameleon/src/chameleon/utils.py", line 426, in get_name
    raise NameError(key)
NameError: it

 - Expression: "it"
 - Filename:   <string>
 - Location:   (line 1: col 19)
 - Arguments:  target_language: <NoneType ('None',) at 0x559931f7d3e0>
               repeat: <RepeatDict ('None',) at 0x7f7e5d9f7820>
```

In order to make this work I have to change that line to something like `i18n:target="string:it"` or i18n:target="python:'it'".

Is this expected?

**Comment by malthe** [comment]
Yes, this is how [Zope Page Templates works](https://zope.readthedocs.io/en/latest/zopebook/ZPT.html), too.

**Comment by ale-rt** [comment]
Thanks a lot @malthe for your reply!

I was expecting  `i18n:target="it"` to behave like `i18n:domain="plone"`, where you do not pass a tal expression, but  I see your point!

Thanks again!
